# Generated by Django 4.2.4 on 2023-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_name', models.CharField(max_length=20)),
                ('is_travel', models.BooleanField()),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
