# Generated by Django 4.2.4 on 2023-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='positive',
        ),
        migrations.AddField(
            model_name='weight',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
